server:
  port: 8081

spring:
  application:
    name: core-service

jwt:
  secret: ${JWT_SECRET:local-dev-only-secret-key-please-change-32bytes-min}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
#배포시 별도 값 주입 필요
